[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name              tail
    Path              /logs/ticket-service.log
    Tag               ticket-service
    Read_from_Head    On
    Refresh_Interval  2

[OUTPUT]
    Name                 es
    Match                *
    Host                 elasticsearch
    Port                 9200
    Index                application-logs
    Logstash_Format      On
    Suppress_Type_Name   On
    Generate_ID          On
