#spring.application.name=CONFIG_SERVER
#
#server.port=8888
#
#spring.profiles.active=native
#
#spring.cloud.config.server.native.searchLocations=file:///Users/abhishek/SpringBoot Project/EmpMngmntAndTktingSystem/config-repo

spring.application.name=CONFIG-SERVER

server.port=8888

spring.cloud.config.server.git.uri=https://github.com/GC3434/employee-ticket-management-config.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true